const dataDoVui = [
    {"q": "Cái gì càng thâm càng hồng?", "options": ["Mắt", "Quả táo", "Gót chân", "Môi"], "c": "Gót chân"},
    {"q": "Con gì không chân mà leo núi vèo vèo?", "options": ["Rắn", "Cá", "Khói", "Sâu"], "c": "Khói"},
    {"q": "Cái gì đen khi bạn mua nó, đỏ khi dùng và xám khi vứt đi?", "options": ["Than", "Sắt", "Gạch", "Quả ớt"], "c": "Than"},
    {"q": "Con gì đập thì sống, không đập thì chết?", "options": ["Con tim", "Con cá", "Con muỗi", "Con quay"], "c": "Con tim"},
    {"q": "Càng kéo càng ngắn là cái gì?", "options": ["Sợi dây", "Điếu thuốc", "Cái chun", "Con đường"], "c": "Điếu thuốc"},
    {"q": "Cái gì bạn có, nhưng người khác dùng nhiều hơn bạn?", "options": ["Tiền", "Cái tên", "Quần áo", "Điện thoại"], "c": "Cái tên"},
    {"q": "Con gì mang được cả miếng gỗ nhưng không mang được hòn sỏi?", "options": ["Con voi", "Con kiến", "Con sông", "Con người"], "c": "Con sông"},
    {"q": "Trái gì không ăn được mà ai cũng sợ?", "options": ["Trái cam", "Trái đất", "Trái bom", "Trái tim"], "c": "Trái bom"},
    {"q": "Cái gì không có miệng mà biết nói?", "options": ["Con vẹt", "Radio", "Cái gương", "Quyển sách"], "c": "Radio"},
    {"q": "Cổ gì dài nhất?", "options": ["Cổ hươu", "Cổ xưa", "Cổ áo", "Cổ tay"], "c": "Cổ xưa"},
    {"q": "Hoa gì biết ăn, biết nói, biết hát?", "options": ["Hoa hồng", "Hoa hậu", "Hoa lan", "Hoa phượng"], "c": "Hoa hậu"},
    {"q": "Cái gì có chân mà không biết đi?", "options": ["Con gà", "Cái bàn", "Đứa trẻ", "Con mèo"], "c": "Cái bàn"},
    {"q": "Bỏ ngoài nướng trong, ăn ngoài bỏ trong là gì?", "options": ["Bánh mì", "Bắp ngô", "Quả cam", "Củ khoai"], "c": "Bắp ngô"},
    {"q": "Lịch nào dài nhất?", "options": ["Lịch vạn niên", "Lịch sử", "Lịch treo tường", "Lịch để bàn"], "c": "Lịch sử"},
    {"q": "Sáng dài, trưa ngắn, chiều lại dài là cái gì?", "options": ["Cái thước", "Cái bóng", "Con đường", "Sợi dây"], "c": "Cái bóng"},
    {"q": "Quần rộng nhất là quần gì?", "options": ["Quần bò", "Quần đùi", "Quần đảo", "Quần vải"], "c": "Quần đảo"},
    {"q": "Con gì không có xương sống mà vẫn đứng thẳng?", "options": ["Con giun", "Con rắn", "Con người", "Con dốc"], "c": "Con dốc"},
    {"q": "Cái gì chặt không đứt, bứt không rời?", "options": ["Sợi dây", "Dòng nước", "Thanh sắt", "Hòn đá"], "c": "Dòng nước"},
    {"q": "Càng cất lại càng thấy?", "options": ["Cất tiền", "Cất nhà", "Cất bước", "Cất tiếng hát"], "c": "Cất nhà"},
    {"q": "Cái gì tay trái cầm được nhưng tay phải không cầm được?", "options": ["Cái cốc", "Khuỷu tay phải", "Điện thoại", "Cây bút"], "c": "Khuỷu tay phải"},
    {"q": "Núi nào bị chặt ra từng khúc?", "options": ["Núi Thái Sơn", "Núi Ngũ Hành Sơn", "Núi Thái Thiết", "Núi Ngũ Nhạc"], "c": "Núi Thái Thiết"},
    {"q": "Cửa gì không có cánh?", "options": ["Cửa sổ", "Cửa biển", "Cửa chính", "Cửa lách"], "c": "Cửa biển"},
    {"q": "Nắng ba năm ta chưa hề bỏ bạn, mưa một ngày bạn lại bỏ ta là gì?", "options": ["Cái ô", "Cái nón", "Cái bóng", "Đôi dép"], "c": "Cái bóng"},
    {"q": "Con gì sinh ra đã biết chữ?", "options": ["Con người", "Con mọt", "Con vẹt", "Con ba ba"], "c": "Con ba ba"},
    {"q": "Cái gì càng rửa càng bẩn?", "options": ["Cái bát", "Cái áo", "Nước", "Đôi tay"], "c": "Nước"},
    {"q": "Cây gì không có lá, không có hoa, không có quả?", "options": ["Cây cột điện", "Cây tre", "Cây nấm", "Cây vàng"], "c": "Cây cột điện"},
    {"q": "Con gì mang cả ngôi nhà trên lưng?", "options": ["Con rùa", "Con ốc sên", "Con kiến", "Con voi"], "c": "Con rùa"},
    {"q": "Cái gì đi nằm, đứng nằm, nằm cũng nằm?", "options": ["Bàn tay", "Bàn chân", "Cái lưng", "Đôi mắt"], "c": "Bàn chân"},
    {"q": "Đường gì không đi được?", "options": ["Đường mòn", "Đường đời", "Đường phèn", "Đường cao tốc"], "c": "Đường phèn"},
    {"q": "Bánh gì không ăn được?", "options": ["Bánh bao", "Bánh xe", "Bánh chưng", "Bánh mì"], "c": "Bánh xe"},
    {"q": "Sông gì không có nước?", "options": ["Sông Lam", "Sông Hồng", "Sông trên bản đồ", "Sông Cửu Long"], "c": "Sông trên bản đồ"},
    {"q": "Con kiến bò lên tai con voi nói gì mà con voi nằm lăn ra chết?", "options": ["Tao giết mày", "Tao có bầu với mày", "Mày béo quá", "Tao đói quá"], "c": "Tao có bầu với mày"},
    {"q": "Cái gì lọt vào tay bạn là bạn sẽ mất nó?", "options": ["Tiền", "Cơ hội", "Bí mật", "Thời gian"], "c": "Bí mật"},
    {"q": "Cái gì không mượn mà trả?", "options": ["Tiền bạc", "Lời nói", "Ơn nghĩa", "Lời chào"], "c": "Lời chào"},
    {"q": "Cái gì luôn đến mà không bao giờ tới?", "options": ["Quá khứ", "Hiện tại", "Ngày mai", "Mùa xuân"], "c": "Ngày mai"},
    {"q": "Quả gì năm mắt năm tay?", "options": ["Quả na", "Quả dứa", "Quả khế", "Quả chuối"], "c": "Quả na"},
    {"q": "Con gì có mũi mà không có mắt, có thân mà không có chân?", "options": ["Con rắn", "Con thuyền", "Con dao", "Cây kim"], "c": "Cây kim"},
    {"q": "Cái gì có cổ mà không có đầu?", "options": ["Con chim", "Cái áo", "Cái bình", "Cái chai"], "c": "Cái áo"},
    {"q": "Con gì không có miệng mà kêu rất to?", "options": ["Con chó", "Con ve sầu", "Cái trống", "Cái còi"], "c": "Cái trống"},
    {"q": "Sơn gì không thể sơn được?", "options": ["Sơn mài", "Sơn tường", "Sơn hà", "Sơn dầu"], "c": "Sơn hà"},
    {"q": "Cái gì càng cắt càng dài?", "options": ["Sợi dây", "Móng tay", "Tóc", "Con đường"], "c": "Con đường"},
    {"q": "Bên trái đường có một căn nhà xanh, bên phải đường có một căn nhà đỏ. Vậy nhà trắng ở đâu?", "options": ["Ở giữa", "Ở Mỹ", "Ở Việt Nam", "Ở sau"], "c": "Ở Mỹ"},
    {"q": "Cá gì nghe tên đã thấy sợ?", "options": ["Cá mập", "Cá cọp", "Cá sấu", "Cá linh"], "c": "Cá cọp"},
    {"q": "Cái gì có lưỡi mà không có miệng?", "options": ["Con dao", "Con rắn", "Cái liềm", "Cái cưa"], "c": "Con dao"},
    {"q": "Trường gì không có học sinh?", "options": ["Trường học", "Trường bắn", "Trường đời", "Trường mẫu giáo"], "c": "Trường bắn"},
    {"q": "Vịt nào đi bằng hai chân?", "options": ["Vịt bầu", "Vịt quay", "Tất cả các con vịt", "Vịt Donald"], "c": "Tất cả các con vịt"},
    {"q": "Cái gì càng nặng càng dễ trôi?", "options": ["Hòn đá", "Con thuyền", "Cái mỏ neo", "Nước"], "c": "Cái mỏ neo"},
    {"q": "Chì nào không viết được?", "options": ["Chì màu", "Chì đen", "Chì lưới", "Chì bấm"], "c": "Chì lưới"},
    {"q": "Cái gì có răng mà không biết nhai?", "options": ["Con chó", "Cái lược", "Cái cưa", "Cái bánh răng"], "c": "Cái lược"},
    {"q": "Con gì càng lớn càng nhỏ?", "options": ["Con kiến", "Con voi", "Con cua", "Con người"], "c": "Con cua"}
];
