const dataVan = [
    {"q": "Từ nào viết đúng chính tả?", "options": ["Sửa soạn", "Xửa soạn", "Sửa xoạn", "Xửa xoạn"], "c": "Sửa soạn"},
    {"q": "Từ nào chỉ hoạt động?", "options": ["Cái bàn", "Chạy bộ", "Đẹp đẽ", "Học sinh"], "c": "Chạy bộ"},
    {"q": "Trong câu 'Mèo đang ngủ', đâu là danh từ?", "options": ["Mèo", "Đang", "Ngủ", "Không có"], "c": "Mèo"},
    {"q": "Từ nào trái nghĩa với 'Cao'?", "options": ["Dài", "To", "Thấp", "Rộng"], "c": "Thấp"},
    {"q": "Đâu là tên riêng viết đúng?", "options": ["việt nam", "Việt nam", "Việt Nam", "việt Nam"], "c": "Việt Nam"},
    {"q": "Từ nào chỉ đặc điểm?", "options": ["Đi", "Xanh lơ", "Uống", "Cặp sách"], "c": "Xanh lơ"},
    {"q": "Câu nào là câu hỏi?", "options": ["Bạn tên là gì?", "Bạn rất giỏi.", "Chào bạn!", "Bạn đang ăn."], "c": "Bạn tên là gì?"},
    {"q": "Từ nào là từ chỉ sự vật?", "options": ["Hát", "Nhảy", "Cây bàng", "Vui vẻ"], "c": "Cây bàng"},
    {"q": "Trái nghĩa với 'Vui' là?", "options": ["Mừng", "Buồn", "Sướng", "Hạnh phúc"], "c": "Buồn"},
    {"q": "Từ nào chỉ trẻ em?", "options": ["Người già", "Thanh niên", "Thiếu nhi", "Phụ huynh"], "c": "Thiếu nhi"},
    {"q": "Bộ phận trả lời câu hỏi 'Ai?' trong câu: 'Lan học giỏi.'", "options": ["Lan", "Học", "Giỏi", "Học giỏi"], "c": "Lan"},
    {"q": "Từ nào đồng nghĩa với 'Chăm chỉ'?", "options": ["Lười biếng", "Cần cù", "Thông minh", "Nhanh nhẹn"], "c": "Cần cù"},
    {"q": "Đâu là câu kiểu 'Ai thế nào?'", "options": ["Lan là học sinh.", "Lan đang hát.", "Lan rất xinh.", "Lan đi học."], "c": "Lan rất xinh."},
    {"q": "Dấu nào dùng để kết thúc câu kể?", "options": ["Dấu hỏi", "Dấu chấm", "Dấu phẩy", "Dấu than"], "c": "Dấu chấm"},
    {"q": "Từ nào viết sai chính tả?", "options": ["Trân trọng", "Chân trọng", "Chân thật", "Trân châu"], "c": "Chân trọng"},
    {"q": "Con vật nào gáy báo thức?", "options": ["Con vịt", "Con gà trống", "Con mèo", "Con chó"], "c": "Con gà trống"},
    {"q": "Từ nào chỉ màu sắc?", "options": ["Tròn", "Méo", "Vàng tươi", "Nóng"], "c": "Vàng tươi"},
    {"q": "Tìm từ chỉ nết tốt của học sinh?", "options": ["Ngoan ngoãn", "Nghịch ngợm", "Lười học", "Quậy phá"], "c": "Ngoan ngoãn"},
    {"q": "Trong câu 'Hoa hồng rất thơm', từ 'thơm' là gì?", "options": ["Danh từ", "Động từ", "Tính từ", "Đại từ"], "c": "Tính từ"},
    {"q": "Điền vào chỗ trống: 'Học... học mãi'", "options": ["Học đi", "Học nữa", "Học luôn", "Học tiếp"], "c": "Học nữa"},
    {"q": "Từ nào chỉ đồ dùng học tập?", "options": ["Cái chổi", "Thước kẻ", "Cái bát", "Cái giường"], "c": "Thước kẻ"},
    {"q": "Từ nào sau đây là từ ghép?", "options": ["Xinh xắn", "Học hành", "Đủng đỉnh", "Lắc lư"], "c": "Học hành"},
    {"q": "Đặt dấu phẩy vào chỗ đúng: 'Lan Hồng Huệ là bạn thân.'", "options": ["Lan Hồng, Huệ", "Lan, Hồng, Huệ", "Lan Hồng Huệ, là", "Không cần"], "c": "Lan, Hồng, Huệ"},
    {"q": "Thành ngữ nào nói về sự đoàn kết?", "options": ["Môi hở răng lạnh", "Ăn quả nhớ kẻ trồng cây", "Lá lành đùm lá rách", "Cả 3 đều đúng"], "c": "Lá lành đùm lá rách"},
    {"q": "Từ 'Sách' là loại từ gì?", "options": ["Danh từ", "Động từ", "Tính từ", "Trạng từ"], "c": "Danh từ"},
    {"q": "Từ nào chỉ người thân trong gia đình?", "options": ["Bạn bè", "Cô giáo", "Ông nội", "Bác sĩ"], "c": "Ông nội"},
    {"q": "Trong câu 'Mẹ đi chợ', 'đi chợ' trả lời cho câu hỏi nào?", "options": ["Làm gì?", "Thế nào?", "Là gì?", "Ở đâu?"], "c": "Làm gì?"},
    {"q": "Đâu là thành ngữ đúng?", "options": ["Mèo khen mèo dài đuôi", "Mèo khen mèo đẹp đuôi", "Mèo khen mèo hay đuôi", "Mèo khen mèo ngắn đuôi"], "c": "Mèo khen mèo dài đuôi"},
    {"q": "Từ trái nghĩa với 'Sạch sẽ' là?", "options": ["Gọn gàng", "Ngăn nắp", "Bẩn thỉu", "Thơm tho"], "c": "Bẩn thỉu"},
    {"q": "Hoa gì tượng trưng cho học trò?", "options": ["Hoa hồng", "Hoa lan", "Hoa phượng", "Hoa huệ"], "c": "Hoa phượng"},
    {"q": "Từ 'Mênh mông' thường dùng tả cái gì?", "options": ["Bút chì", "Cái thước", "Cánh đồng", "Quyển vở"], "c": "Cánh đồng"},
    {"q": "Điền từ: 'Lù lù như...'", "options": ["Con voi", "Con gấu", "Con rùa", "Con kiến"], "c": "Con voi"},
    {"q": "Tìm từ viết đúng?", "options": ["Dành dụm", "Giành dụm", "Dành giụm", "Giành giụm"], "c": "Dành dụm"},
    {"q": "Dấu nào dùng để ngăn cách các ý trong câu?", "options": ["Dấu chấm", "Dấu phẩy", "Dấu ngoặc kép", "Dấu hai chấm"], "c": "Dấu phẩy"},
    {"q": "Từ nào là từ láy?", "options": ["Học tập", "Xinh xắn", "Nhà cửa", "Xe cộ"], "c": "Xinh xắn"},
    {"q": "Cây gì được dùng làm biểu tượng của làng quê Việt Nam?", "options": ["Cây bàng", "Cây đa", "Cây phượng", "Cây dừa"], "c": "Cây đa"},
    {"q": "Từ 'Thầy giáo' chỉ gì?", "options": ["Đồ vật", "Con vật", "Người", "Cây cối"], "c": "Người"},
    {"q": "Câu 'Em là học sinh lớp 2' thuộc kiểu câu nào?", "options": ["Ai làm gì?", "Ai là gì?", "Ai thế nào?", "Câu hỏi"], "c": "Ai là gì?"},
    {"q": "Từ 'Đỏ rực' chỉ gì?", "options": ["Hoạt động", "Hình dáng", "Màu sắc", "Âm thanh"], "c": "Màu sắc"},
    {"q": "Con gì là biểu tượng của hòa bình?", "options": ["Đại bàng", "Chim bồ câu", "Chim sẻ", "Chim công"], "c": "Chim bồ câu"},
    {"q": "Từ nào chỉ hành động trong lớp?", "options": ["Ngủ gật", "Giơ tay phát biểu", "Đá bóng", "Bơi lội"], "c": "Giơ tay phát biểu"},
    {"q": "Điền tiếp: 'Công cha như núi...'", "options": ["Trường Sơn", "Thái Sơn", "Fansipan", "Đồi cao"], "c": "Thái Sơn"},
    {"q": "Từ nào dùng tả giọng hát?", "options": ["Trong trẻo", "Vuông vắn", "Xanh biếc", "Thơm ngát"], "c": "Trong trẻo"},
    {"q": "Loài hoa nào nở vào mùa xuân?", "options": ["Hoa đào", "Hoa phượng", "Hoa cúc", "Hoa lan"], "c": "Hoa đào"},
    {"q": "Từ 'Trắng muốt' dùng tả cái gì?", "options": ["Bầu trời", "Bộ lông con cò", "Mặt đất", "Cái lá"], "c": "Bộ lông con cò"},
    {"q": "Tìm từ viết sai?", "options": ["Sản xuất", "Sửa sang", "Sử lý", "Sứ giả"], "c": "Sử lý"},
    {"q": "Từ trái nghĩa với 'Nhanh'?", "options": ["Lẹ", "Chậm", "Vội", "Mau"], "c": "Chậm"},
    {"q": "Câu 'Trường học là ngôi nhà thứ hai' dùng biện pháp gì?", "options": ["So sánh", "Nhân hóa", "Ẩn dụ", "Không có"], "c": "So sánh"},
    {"q": "Từ nào chỉ tính cách?", "options": ["Đi đứng", "Hiền lành", "Quần áo", "Trường học"], "c": "Hiền lành"},
    {"q": "Từ 'Gia đình' có mấy tiếng?", "options": ["1", "2", "3", "4"], "c": "2"}
];
